steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', '-d']
    env: ['GOPATH=/go']
    volumes:
    - name: 'go'
      path: '/go'

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    env: ['GOPATH=/go']
    volumes:
    - name: 'go'
      path: '/go'
timeout: "1600s"